# Generated by Django 5.0.6 on 2024-06-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_events", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["schedulted_for"]},
        ),
        migrations.RenameField(
            model_name="event",
            old_name="creation_date",
            new_name="created",
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_date",
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_time",
        ),
        migrations.AddField(
            model_name="event",
            name="schedulted_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
