# Generated by Django 5.0.6 on 2024-06-01 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_events", "0002_alter_event_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="created",
            new_name="date_created",
        ),
    ]
