# Generated by Django 5.0.6 on 2024-06-01 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_events", "0003_rename_created_event_date_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["scheduled"]},
        ),
        migrations.RenameField(
            model_name="event",
            old_name="schedulted_for",
            new_name="scheduled",
        ),
    ]
