# Generated by Django 5.0.6 on 2024-06-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_events", "0004_alter_event_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="scheduled",
            field=models.DateField(blank=True, null=True),
        ),
    ]
