# Generated by Django 5.0.6 on 2024-06-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_events", "0005_alter_event_scheduled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="scheduled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
