# Generated by Django 5.0.6 on 2024-06-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendar_events", "0006_alter_event_scheduled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["scheduled_date"]},
        ),
        migrations.RemoveField(
            model_name="event",
            name="scheduled",
        ),
        migrations.AddField(
            model_name="event",
            name="scheduled_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="scheduled_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
