# Generated by Django 5.0.6 on 2024-05-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
