# Generated by Django 5.0.1 on 2024-06-04 09:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "photo_gallery",
            "0002_alter_photopost_options_photopost_upload_date_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="photopost",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="photopost",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="liked_photo_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
