# Generated by Django 5.0.1 on 2024-06-04 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_gallery", "0005_remove_photopost_authorized_photoauth"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="photopost",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_photo_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
