# Generated by Django 5.0.1 on 2024-06-05 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_gallery", "0006_alter_photopost_likes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoauth",
            name="photo_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="auths",
                to="photo_gallery.photopost",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="photopost",
            name="image",
            field=models.ImageField(null=True, upload_to="photo-gallery/"),
        ),
        migrations.AlterField(
            model_name="photopost",
            name="likes",
            field=models.ManyToManyField(
                blank=True,
                related_name="liked_photo_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
