# Generated by Django 5.0.1 on 2024-06-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_gallery", "0008_alter_photopost_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photopost",
            options={"ordering": ["-upload_date"]},
        ),
        migrations.AddField(
            model_name="photoauth",
            name="details",
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name="photoauth",
            name="upload_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="photopost",
            name="title",
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
    ]
