# Generated by Django 5.0.1 on 2024-06-05 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photo_gallery", "0010_alter_photoauth_options_photoauth_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photoauth",
            name="status",
        ),
    ]
