# Generated by Django 5.0.1 on 2024-06-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photo_gallery", "0011_remove_photoauth_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photoauth",
            options={"ordering": ["-upload_date", "status"]},
        ),
        migrations.RemoveField(
            model_name="photoauth",
            name="authorized",
        ),
        migrations.AddField(
            model_name="photoauth",
            name="status",
            field=models.CharField(
                choices=[
                    ("1", "Підтверджено"),
                    ("0", "Йде перевірка"),
                    ("-1", "Відхилино"),
                ],
                default="0",
                max_length=31,
            ),
        ),
    ]
