# Generated by Django 5.0.6 on 2024-05-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'Advert', 'verbose_name_plural': 'Adverts'},
        ),
        migrations.AddField(
            model_name='advert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
