# Generated by Django 5.0.6 on 2024-06-01 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adverts", "0002_alter_advert_options_advert_created"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advert",
            options={
                "ordering": ["-created"],
                "verbose_name": "Advert",
                "verbose_name_plural": "Adverts",
            },
        ),
    ]
