# Generated by Django 5.0.4 on 2024-06-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_portfolio_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='adress',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
