# Generated by Django 5.0.4 on 2024-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_image_image_alter_portfolio_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='projects',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='user.project'),
        ),
    ]
