# Generated by Django 5.0.4 on 2024-06-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_portfolio_projects_portfolio_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='portfolio', to='user.project'),
        ),
    ]
