# Generated by Django 5.0.4 on 2024-06-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_portfolio_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='avatars/default/default.png', upload_to='project_imgs/'),
        ),
    ]
